# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntest.proto\"w\n\x0cTest_Request\x12\x0e\n\x06number\x18\x01 \x03(\x05\x12\"\n\x05image\x18\x02 \x03(\x0b\x32\x13.Test_Request.Image\x1a\x33\n\x05Image\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0b\n\x03img\x18\x03 \x01(\x0c\"!\n\rTest_Response\x12\x10\n\x08response\x18\x01 \x01(\x08\x32\x36\n\x04Test\x12.\n\x0bTest_Getmsg\x12\r.Test_Request\x1a\x0e.Test_Response\"\x00\x62\x06proto3'
)




_TEST_REQUEST_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='Test_Request.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='Test_Request.Image.height', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='Test_Request.Image.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='img', full_name='Test_Request.Image.img', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=133,
)

_TEST_REQUEST = _descriptor.Descriptor(
  name='Test_Request',
  full_name='Test_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='Test_Request.number', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='Test_Request.image', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TEST_REQUEST_IMAGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=133,
)


_TEST_RESPONSE = _descriptor.Descriptor(
  name='Test_Response',
  full_name='Test_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='Test_Response.response', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=168,
)

_TEST_REQUEST_IMAGE.containing_type = _TEST_REQUEST
_TEST_REQUEST.fields_by_name['image'].message_type = _TEST_REQUEST_IMAGE
DESCRIPTOR.message_types_by_name['Test_Request'] = _TEST_REQUEST
DESCRIPTOR.message_types_by_name['Test_Response'] = _TEST_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Test_Request = _reflection.GeneratedProtocolMessageType('Test_Request', (_message.Message,), {

  'Image' : _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
    'DESCRIPTOR' : _TEST_REQUEST_IMAGE,
    '__module__' : 'test_pb2'
    # @@protoc_insertion_point(class_scope:Test_Request.Image)
    })
  ,
  'DESCRIPTOR' : _TEST_REQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:Test_Request)
  })
_sym_db.RegisterMessage(Test_Request)
_sym_db.RegisterMessage(Test_Request.Image)

Test_Response = _reflection.GeneratedProtocolMessageType('Test_Response', (_message.Message,), {
  'DESCRIPTOR' : _TEST_RESPONSE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:Test_Response)
  })
_sym_db.RegisterMessage(Test_Response)



_TEST = _descriptor.ServiceDescriptor(
  name='Test',
  full_name='Test',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=170,
  serialized_end=224,
  methods=[
  _descriptor.MethodDescriptor(
    name='Test_Getmsg',
    full_name='Test.Test_Getmsg',
    index=0,
    containing_service=None,
    input_type=_TEST_REQUEST,
    output_type=_TEST_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEST)

DESCRIPTOR.services_by_name['Test'] = _TEST

# @@protoc_insertion_point(module_scope)
